name: Ruby

env:
  GROQ_API_KEY: 'Value Not Required in CI'

on:
  push:
    branches:
      - 'develop'

  # allow CI on any pull request
  pull_request:
    branches:
      - '*'

jobs:
  build:
    runs-on: ubuntu-latest
    name: Ruby ${{ matrix.ruby }}
    strategy:
      matrix:
        ruby:
          - '3.1.5'
          - '3.3.1'

    steps:
    - uses: actions/checkout@v4
    - name: Set up Ruby
      uses: ruby/setup-ruby@v1
      with:
        ruby-version: ${{ matrix.ruby }}
        bundler-cache: true
    - name: Run the default task
      run: bundle exec rake
    - name: Run the test suite with lower Faraday versions
      run: FARADAY_VERSION=1.10.3 bin/setup && bundle exec rake test